### 1) 게시글 등록
POST http://localhost:8080/api/posts
Accept: application/json
Content-Type: application/json

{
  "title": "제목입니다.",
  "content": "게시글 내용입니다."
}

### 2) 게시글 목록 조회 (검색 + 페이징)
GET http://localhost:8080/api/posts?keyword={{$random.word}}&page=0&size=5
Accept: application/json

{
  "conditions": [
    { "field":"email","operator":"like","value":"test@example.com" }
  ],
  "pageInfo": {
    "currentPage":0,
    "pageSize":5,
    "totalElements":0,
    "totalPages":0
  }
}


### 3) 단건 게시글 조회
GET http://localhost:8080/api/posts/{{$random.integer(1,10)}}
Accept: app
### 4) 게시lication/json
글 수정
PUT http://localhost:8080/api/posts/{{$random.integer(1,10)}}
Accept: application/json
Content-Type: application/json

{
  "title": "{{$random.words(2, 4)}} (수정됨)",
  "content": "{{$random.text(50, 100)}} (수정된 내용)"
}

### 5) 게시글 삭제
DELETE http://localhost:8080/api/posts/{{$random.integer(1,10)}}
Accept: application/json
